### ISSUE TITLE
the project does not work on 30.04.2022

### ISSUE THREAD

**Issue by Depter30** [hkpanchani/Bulk-Whatsapp-Sender#8]
After authorization on the page web.whatsapp.com messages are not being sent.
Pls HELP

**Comment by Depter30** [comment]
Thanks.
But, I cant send media
"Traceback (most recent call last):
  File "C:\Bulk-Whatsapp-Sender-master\Bulk Whatsapp Sender.py", line 276, in execute_script
    wa.encodeMedia(mediaPath)
  File "C:\Bulk-Whatsapp-Sender-master\whatsArcCore.py", line 71, in encodeMedia
    mime = magic.Magic(mime=True)
  File "C:\Users\└ьшЁїрэ\AppData\Local\Programs\Python\Python38\lib\site-packages\magic\magic.py", line 71, in __init__
    magic_load(self.cookie, magic_file)
  File "C:\Users\└ьшЁїрэ\AppData\Local\Programs\Python\Python38\lib\site-packages\magic\magic.py", line 272, in magic_load
    return _magic_load(cookie, coerce_filename(filename))
  File "C:\Users\└ьшЁїрэ\AppData\Local\Programs\Python\Python38\lib\site-packages\magic\magic.py", line 203, in errorcheck_negative_one
    raise MagicException(err)
magic.magic.MagicException: b'could not find any valid magic files!'"
